# Generated by Django 4.1.3 on 2022-11-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0002_viajes_delete_viajesfamiliares'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='viajes',
            new_name='Excursion',
        ),
    ]
