# Generated by Django 4.1.3 on 2022-11-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_documentacion_excursiones_recreadores_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excursiones',
            new_name='Excursion',
        ),
    ]
