# Generated by Django 4.1.3 on 2022-11-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0005_rename_excursiones_excursion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='lugar',
            new_name='nombre',
        ),
    ]
